services:
  todoapp:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/cmd/todoapp/Dockerfile
    container_name: todoapp
    environment:
      - HTTP_ADDR=:5050
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - LOGGER_FOLDER=/app/out/logs
      - POSTGRES_HOST=todoapp-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - TIME_ZONE=${TIME_ZONE}
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    ports:
      - "5050:5050"
    restart: always

  todoapp-postgres:
    image: postgres:18.4-bookworm
    container_name: todoapp-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always
  todoapp-postgres-migrate:
    image: migrate/migrate:v4.19.1
    container_name: todoapp-migrate-postgres
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
  port-forwarder:
    image: alpine/socat:1.8.1.3
    container_name: todoapp-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:todoapp-postgres:5432
    ports:
      - "127.0.0.1:5432:5432"
